# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/derek/school/compilers/project1/compilers1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/derek/school/compilers/project1/compilers1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek/school/compilers/project1/compilers1/CMakeFiles /home/derek/school/compilers/project1/compilers1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek/school/compilers/project1/compilers1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project1

# Build rule for target.
project1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project1
.PHONY : project1

# fast build rule for target.
project1/fast:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/build
.PHONY : project1/fast

lib/AutomataState.o: lib/AutomataState.cpp.o

.PHONY : lib/AutomataState.o

# target to build an object file
lib/AutomataState.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/AutomataState.cpp.o
.PHONY : lib/AutomataState.cpp.o

lib/AutomataState.i: lib/AutomataState.cpp.i

.PHONY : lib/AutomataState.i

# target to preprocess a source file
lib/AutomataState.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/AutomataState.cpp.i
.PHONY : lib/AutomataState.cpp.i

lib/AutomataState.s: lib/AutomataState.cpp.s

.PHONY : lib/AutomataState.s

# target to generate assembly for a file
lib/AutomataState.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/AutomataState.cpp.s
.PHONY : lib/AutomataState.cpp.s

lib/Lexer.o: lib/Lexer.cpp.o

.PHONY : lib/Lexer.o

# target to build an object file
lib/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/Lexer.cpp.o
.PHONY : lib/Lexer.cpp.o

lib/Lexer.i: lib/Lexer.cpp.i

.PHONY : lib/Lexer.i

# target to preprocess a source file
lib/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/Lexer.cpp.i
.PHONY : lib/Lexer.cpp.i

lib/Lexer.s: lib/Lexer.cpp.s

.PHONY : lib/Lexer.s

# target to generate assembly for a file
lib/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/Lexer.cpp.s
.PHONY : lib/Lexer.cpp.s

lib/utilities.o: lib/utilities.cpp.o

.PHONY : lib/utilities.o

# target to build an object file
lib/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/utilities.cpp.o
.PHONY : lib/utilities.cpp.o

lib/utilities.i: lib/utilities.cpp.i

.PHONY : lib/utilities.i

# target to preprocess a source file
lib/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/utilities.cpp.i
.PHONY : lib/utilities.cpp.i

lib/utilities.s: lib/utilities.cpp.s

.PHONY : lib/utilities.s

# target to generate assembly for a file
lib/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/lib/utilities.cpp.s
.PHONY : lib/utilities.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/testSuite.o: src/testSuite.cpp.o

.PHONY : src/testSuite.o

# target to build an object file
src/testSuite.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/testSuite.cpp.o
.PHONY : src/testSuite.cpp.o

src/testSuite.i: src/testSuite.cpp.i

.PHONY : src/testSuite.i

# target to preprocess a source file
src/testSuite.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/testSuite.cpp.i
.PHONY : src/testSuite.cpp.i

src/testSuite.s: src/testSuite.cpp.s

.PHONY : src/testSuite.s

# target to generate assembly for a file
src/testSuite.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/src/testSuite.cpp.s
.PHONY : src/testSuite.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... project1"
	@echo "... lib/AutomataState.o"
	@echo "... lib/AutomataState.i"
	@echo "... lib/AutomataState.s"
	@echo "... lib/Lexer.o"
	@echo "... lib/Lexer.i"
	@echo "... lib/Lexer.s"
	@echo "... lib/utilities.o"
	@echo "... lib/utilities.i"
	@echo "... lib/utilities.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/testSuite.o"
	@echo "... src/testSuite.i"
	@echo "... src/testSuite.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

